export const TeamData = [
  {
    name: "Miss Wajiha Mughal",
    post: "Supervizor",
    image: "/image/b.png",
    // fbid: "/hhh",
    // twtterid: "/jhg",
    // instaid: "/hdgf",
    // linkinid: "/dhgf",
  },
  {
    name: "Liaqat Shehzad",
    post: "Student",
    image: "/image/a.png",
    // fbid: "/hhh",
    // twtterid: "/jhg",
    // instaid: "/hdgf",
    // linkinid: "/dhgf",
  },
  {
    name: "Musharaff Shakoor",
    post: "Student",
    image: "/image/c.png",
    // fbid: "/hhh",
    // twtterid: "/jhg",
    // instaid: "/hdgf",
    // linkinid: "/dhgf",
  },
  {
    name: "Usama Ali",
    post: "Student",
    image: "/image/usama.png",
    // fbid: "/hhh",
    // twtterid: "/jhg",
    // instaid: "/hdgf",
    // linkinid: "/dhgf",
  },
];
